# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Generate References

on:
  workflow_dispatch:

jobs:
  references:
    name: Generate References
    runs-on: ubuntu-22.04
    if: >
      github.event_name == 'push' && contains(github.event.head_commit.message, '[generate-references]')
    steps:
      - uses: actions/checkout@v3
      - name: Download Dependencies
        run: |
          sudo apt update -qq
          sudo apt install gettext imagemagick -qq
      - name: Build Burn-My-Windows
        run: make
      - name: Generate References
        run: sudo make references
      - uses: actions/upload-artifact@v3
        with:
          name: references
          path: tests/references/
